# -*- coding: utf-8 -*-
"""Astar_template.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ek7fvJxb6qwJrwBW_-tm7veTyQWhW0jU
"""

import math
from queue import PriorityQueue

coords = {} # node id is the key
adjlist = {} # node id is the key
with open('input.txt','r') as f:
    V = int(f.readline())
    for i in range(V):
        strs = f.readline().split()
        nid, x, y = strs[0], int(strs[1]), int(strs[2])
        coords[nid] = (x, y) # x, y kept as a tuple
        adjlist[nid] = [] #create empty list for each node's adjnodes

    E = int(f.readline())
    for i in range(E):
        strs = f.readline().split()
        n1, n2, c = strs[0], strs[1], int(strs[2])
        adjlist[n1].append((n2, c)) # (n2, c) tuple
    startnid = f.readline().rstrip()
    goalnid = f.readline().rstrip()

print('graph')
for nid in adjlist:
    print(nid, coords[nid], '--->',  adjlist[nid])
    for tup in adjlist[nid]:
        print('\t', tup[0], tup[1])
print('start', startnid, 'goal', goalnid)

coords['D']

adjlist['C']

def heuristic():
    # complete it yourself

class State:
    # Constructor
        # nid, g, f, parent ...

class C:
    ___init


        self.id =
        self.parent = state
        self.g
        self.f

    __lt__

    __eq__

    __str__



start = C('S', None, 0, 0+heuristic(start))

while ...
    curr = .. gt

    .... solution

	For each node M adjacent to node currstate.node do
        g ← currstate.g + edge_cost(currstate.node, M)
		h ←  euclidean_distance(M, goalnode)
		f ← g+h
		create newstate(M, g, f, parent=currstate)
		insert newstate to minQ



from queue import PriorityQueue

q = PriorityQueue()

# q.put( (f, state) )
q.put( (4, 5, 'Read') )
q.put( (2, 2, 'Play') )
q.put( (4, 4, 'Write') )
q.put( (4, 6, 'Listen') )
q.put( (1, 1, 'Code') )
q.put( (3, 3, 'Study') )

while not q.empty():
    tup = q.get()
    print(tup[0], tup[1])

from queue import PriorityQueue


class C:
    def __init__(self, a, b):
        self.a = a
        self.b = b

    def __lt__(self, other):
        return self.b > other.b

    def __eq__(self, other):
        return self.a==other.a and self.b==other.b


c1 = C(1, 2)
c2 = C(1, 2)
c3 = C(1, 3)
c4 = C(3, 2)
q = PriorityQueue()
# q.put( state )
q.put(c1)
q.put(c2)
q.put(c3)
q.put(c4)
while not q.empty():
    c = q.get()
    print(c.a, c.b)

from types import NoneType
G = goal_state

A = goal_state.parent

B = A.parent
...

S  = X.parent

S.parent = None

S ..... B A G